import Navbar from '@/components/Navbar';
import SiteFooter from '@/components/SiteFooter';
import SmoothScroll from '@/components/SmoothScroll';

export const metadata = {
  title: 'Terms of Service · Taskmaverick',
  description: 'The terms that govern your access to and use of the Taskmaverick service.',
};

// Numbered clause: "1.1  Platform: …"
function Clause({ n, term, children }) {
  return (
    <div className="legal-clause">
      <span className="legal-no">{n}</span>
      <p>
        {term ? <b>{term}</b> : null} {children}
      </p>
    </div>
  );
}

export default function TermsPage() {
  return (
    <div className="page">
      <Navbar />
      <SmoothScroll>
      <main className="legal">
        <header className="legal-head">
          <p className="legal-kicker">Taskmaverick</p>
          <h1>Terms of Service</h1>
          <p className="legal-updated">Last updated: August 19, 2026</p>
        </header>

        <div className="legal-intro">
          <p>
            These Terms of Service, and any related agreements and Privacy Policies, are a legal
            agreement (&ldquo;Agreement&rdquo;) made between you, either as a Customer, visitor,
            Consultant, account administrator (&ldquo;Admin&rdquo;), User, and Taskmaverick, Inc.,
            (&ldquo;Taskmaverick,&rdquo; &ldquo;Company,&rdquo; &ldquo;we,&rdquo; or &ldquo;us&rdquo;)
            for the use of the Taskmaverick.com website and the Taskmaverick mobile application, and
            all related services, features and Content offered by the Company (collectively, the
            &ldquo;Service&rdquo;).
          </p>
          <p>
            These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of our
            Service. Your access to and use of the Service is conditioned on your acceptance of and
            compliance with these Terms. These Terms apply to all who visit, access, or use the
            Service.
          </p>
        </div>

        <section className="legal-section">
          <h2>1.0 Definitions</h2>
          <Clause n="1.1" term="Platform:">The Platform (alternatively referred to hereinafter as the &ldquo;Service&rdquo; or the &ldquo;Software&rdquo;) is defined as any and all features, functions, and services provided by Taskmaverick.</Clause>
          <Clause n="1.2" term="Organization:">The legal entity which is subscribed to The Platform, or &ldquo;Customer&rdquo;.</Clause>
          <Clause n="1.3" term="Library:">The content database where information can be stored and organized in the form of Missions.</Clause>
          <Clause n="1.4" term="Marketplace:">The content database from which readily-made Missions can be imported into Customer&rsquo;s Organization Library.</Clause>
          <Clause n="1.5" term="Mission:">A mission can be in several forms, including Task, Checklist, Survey, Ticket, Audit, Test, or Media.</Clause>
          <Clause n="1.6" term="Process:">A Process is an aggregation of Missions which can be assigned or posted automatically in sequence, based on a variety of conditions, such as the occurrence, the aging, or the rating of prior Mission(s), or information collected in prior Mission(s).</Clause>
          <Clause n="1.7" term="Trigger Instance:">A Trigger Instance can be either an assignment of a Mission, or it can be an action that is triggered within the Platform, or through the Platform into a third-party system, based on an automation within the Platform.</Clause>
          <Clause n="1.8" term="User:">A User is a person or an individual who can perform in the Platform. A User can be set up as follows:</Clause>
          <ul className="legal-sub">
            <li>To have access only to Team Boards</li>
            <li>To have access only to a Personal Board</li>
            <li>To have access to both a Personal Board and Team Boards</li>
          </ul>
          <Clause n="1.9" term="Personal Board:">A User can be provided with access to a dedicated Personal Board where missions can be assigned to them.</Clause>
          <Clause n="1.10" term="Course:">A Course is an aggregation of Missions which can be assigned or posted automatically in sequence, based on a variety of conditions, such as the occurrence of prior Mission(s).</Clause>
          <Clause n="1.11" term="Certification:">A Certificate can be created, tracked, and managed by the Platform, and corresponding actions can be taken by the User on their Personal Board. A Certificate can include Courses and Missions.</Clause>
          <Clause n="1.12" term="Storage:">The number of gigabytes (GB) that is used by an Organization to store content in the Platform.</Clause>
          <Clause n="1.13" term="Location:">A Location can be comprised of one Business Unit, or multiple Business Units.</Clause>
          <Clause n="1.14" term="Business Unit:">A Business Unit or Unit can be comprised of any of the following:</Clause>
          <ul className="legal-sub">
            <li>One Location with one or more Team Boards, or Users.</li>
            <li>One Location with one or more Buildings, or Users.</li>
            <li>One Building with one or more Areas, or Users.</li>
            <li>One Building with one or more Team Boards, or Users.</li>
            <li>One Area with one or more Team Boards, or Users.</li>
          </ul>
          <Clause n="1.15" term="Team Board Template:">A Team Board Template can be created in the Platform, with Missions added to it. A Team Board Template does not have Users added to it, and it does not belong to any Unit.</Clause>
          <Clause n="1.16" term="Team Board:">A Team Board Template automatically becomes a unique Team Board every time it becomes activated under a Location, or under a Building, or under an Area. The Missions included in a Team Board Template remain the same when such template becomes a Team Board, except that the Missions with each Team Board can have unique assignment schedules, and Users can be added to a Team Board, but not to a Team Board template. One or multiple Users can belong to a Team Board.</Clause>
          <Clause n="1.17" term="Ticket Board:">A Ticket Board is where alerts are posted in the form of Tickets. One or multiple Users can belong to a Ticket Board. For billing purposes, a Ticket Board shall have the same base cost as a Team Board, and it shall be counted as a Team Board in any billing formula.</Clause>
          <Clause n="1.18" term="Active or Inactive:">Any Unit, Team Board, Personal Board or User is deemed as &ldquo;Active&rdquo; or &ldquo;Inactive&rdquo; based on its designation in the Platform. Taskmaverick&rsquo;s Subscription Fee shall be applied in full during any partial or full month when a feature or function is active, and regardless of whether Customer is deriving any benefit from such feature or function. No fees shall be applied to any feature or function which becomes designated as &ldquo;Inactive&rdquo; in the Platform for the entirety of a calendar month. Customer may, from time to time, either activate or deactivate billable features or functions. In the event of such activations or deactivations, Customer&rsquo;s billing shall be automatically adjusted without further notice to Customer.</Clause>
        </section>

        <section className="legal-section">
          <h2>2.0 Subscription Fees Payment</h2>
          <Clause n="2.1" term="Subscription Only:">The Service is provided on a subscription basis for the term specified in your subscription, in accordance with the respective subscription plan purchased (the &ldquo;Subscription&rdquo;).</Clause>
          <Clause n="2.2" term="Subscription Fees:">Such fees shall be according to Taskmaverick&rsquo;s conditions and published rates on its website at www.taskmaverick.com, unless agreed to otherwise through a subscription offering, or via an Order Form, or through an alternative written agreement that is signed by Taskmaverick. Taskmaverick may amend its published rates at anytime with or without notice to Customer. Should the published rates be amended by Taskmaverick during any given month, then such rates may, at Taskmaverick&rsquo;s discretion, be applied to Customer during the following month, unless expressly agreed to otherwise with Customer through a subscription offering, or via an Order Form, or through an alternative written agreement that is signed by Taskmaverick.</Clause>
          <Clause n="2.3" term="Deleting vs Deactivating:">If a Unit, Team Board, Ticket Board, Personal Board, or User are deleted, their related data will be completely removed from the system. If such are inactive, then the Software will continue to store all data related to them, and they can therefore be reactivated at any time.</Clause>
          <Clause n="2.4" term="Billing:">After each calendar month when billing is applicable under this Agreement, the amounts owed by Customer will be debited automatically, based on Customer&rsquo;s payment method and information. If expressly agreed to in writing, Customer will receive an invoice via email, and Customer shall remit payment accordingly.</Clause>
          <Clause n="2.5" term="Termination for Non-Payment:">In the event that Taskmaverick is unable to collect the Fees owed by Customer under this Agreement, or if Taskmaverick experiences a decline, chargeback or other rejection of a charge of any amounts due, Taskmaverick may, at its sole discretion, suspend or cancel the service provided under this Agreement, without any further notice, and without derogating from any other remedy that may be applicable to Taskmaverick under this Agreement.</Clause>
          <Clause n="2.6" term="Effect of Termination of Service:">Upon the termination or expiration of these Terms, all rights granted to Customer under this Agreement shall terminate. It is Customer&rsquo;s sole responsibility to export the Customer Data, which we will continue to store for a period of thirty (30) calendar days after such termination or expiration. Thereafter, Taskmaverick reserves the right, at its sole discretion, to delete such Customer Data, without any further liability to Customer. In no event shall the termination or expiration of this Agreement relieve Customer from its payment obligations.</Clause>
          <Clause n="2.7" term="Taxes:">The Subscription Fees are exclusive of any and all taxes. (Including without limitation, value-added tax, sales tax, use tax, excise, goods and services tax, etc.), levies, or duties, hereunder (the &ldquo;Taxes&rdquo;). If you chose to use our Service while being located in a jurisdiction that requires you to deduct or withhold taxes or other amounts from any amounts due to us, you hereby agree that Taskmaverick will add such Taxes to your Subscription Fees. Such addition will be in a manner and amount necessary to ensure that our net proceeds are equal to the amounts we would have received, based on the Subscription Order Form, had such Taxes not been applicable.</Clause>
          <Clause n="2.8" term="Excessive or Abusive Usage:">We shall have the right, including without limitation, where we, at our sole discretion, believe that you and/or any of your Users have misused the Service or otherwise excessively use the Service compared to the anticipated everyday use. At our sole discretion, we may offer the Subscription on a different pricing scale and/or impose additional restrictions as to the upload, storage, download, and use of the Service. The additional restrictions are, without limitation, restrictions on Third Party Services, network traffic, bandwidth, size and/or length of Content, quality and/or format of Content, sources of Content, the volume of download time, etc.</Clause>
          <Clause n="2.9" term="Hardware:">You shall source the necessary devices (phone, tablet, accessories, etc.) to interact with the Software. Taskmaverick may, from time to time, recommend hardware suppliers to Customer, but Customer shall have the option to purchase from anywhere. A recommendation of a vendor by Taskmaverick shall not imply a warranty by Taskmaverick.</Clause>
        </section>

        <section className="legal-section">
          <h2>3.0 Your Use of the Service</h2>
          <Clause n="3.1" term="Terms of Access:">By accessing or using the Service, you agree to be bound by these Terms. If you are using the Services on behalf of an organization or entity (&ldquo;Organization&rdquo;), then you agree to these Terms on behalf of that Organization, and you represent and warrant that you have the authority to bind the Organization to these Terms. In that case, &ldquo;you&rdquo; and &ldquo;your&rdquo; refers to you and that Organization. These Terms become legally binding upon you personally and upon any entity that you represent, as of the date that any service provided by Taskmaverick is used (the &ldquo;Effective Date&rdquo;) by either of you.</Clause>
          <Clause n="3.2" term="Binding Terms:">You may use the Service only if you agree to be bound by these Terms of Service and all applicable local, state, national, and international laws, rules, and regulations. The Service may change from time to time as we evolve, refine, or add more features to the Service, often without prior notice to you.</Clause>
        </section>

        <section className="legal-section">
          <h2>4.0 Registration &amp; Administration</h2>
          <Clause n="4.1" term="Administrator:">The first User who creates an account (&ldquo;Account&rdquo;) and registers to the Service is automatically assigned as the Administrator (or &ldquo;Admin&rdquo;). The Admin is also considered a User of the Service. Taskmaverick will not be responsible for any losses to you caused by any unauthorized access or usage of the account.</Clause>
          <Clause n="4.2" term="Authorized Access:">We consider the Administrators (or Admin; or Admins) as the authorized representative(s) of the enrolling entity as well as any person who gains access through the Admin&rsquo;s access credentials, whether voluntarily or otherwise. Any access to the Service through valid credentials is construed to be authorized access until we are informed and can confirm otherwise. An Admin&rsquo;s actions and decisions, along with the actions and decisions of anyone granted access by an Admin, shall be legally binding on each entity for which they are the Admin.</Clause>
        </section>

        <section className="legal-section">
          <h2>5.0 Your Account</h2>
          <Clause n="5.1" term="Accessibility:">You must provide accurate information when you create your Taskmaverick account. Your Taskmaverick account gives you access to the Services and functionality that we may establish and maintain from time to time and at our sole discretion. We may maintain different types of accounts or account setups for different types of users or organizations, depending on how they choose to use our Service. If you connect to Taskmaverick with a third-party service, you give us permission to access and use your information from that Service as permitted by that Service and to store your login credentials for that Service. You may never use another user&rsquo;s account without permission.</Clause>
        </section>

        <section className="legal-section">
          <h2>6.0 Account Security &amp; Privacy</h2>
          <Clause n="6.1" term="Credentials:">You are responsible for safeguarding the credentials that you use to access the Service and for any activities or actions under your password, whether your password is with Taskmaverick or a third-party service. We encourage you to use &ldquo;strong&rdquo; passwords that use a combination of upper- and lowercase letters, numbers, and symbols with your account. Current NIST standards recommend password lengths of at least eight characters. You agree not to disclose your password to any third party. Taskmaverick cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements. You must notify Taskmaverick immediately upon becoming aware of any breach of security or unauthorized use of your account.</Clause>
          <Clause n="6.2" term="Security:">Your security is important to us. Some of the security features we utilize include utilizing isolated networks deployed in a Virtual Privacy Cloud with dedicated firewalls, sophisticated role access rules, and end-to-end encryption using the reliable Transport Layer Security (TLS). Also, our database provider is ISO/IEC 27001:2013 certified as well as PCI DSS compliant. Although we do our best to provide robust security, we do not guarantee that we can fully protect such data, and we, as a result of this, advise you that using the system shall be done at your own risk.</Clause>
          <Clause n="6.3" term="Personal Information:">We routinely collect and use certain Personal Information about our Users to provide services to them or improve our Service. We do not sell or purposely share that data with any third party, except as part of servicing or improving the system. Users can find information regarding our Privacy Policy at the following link: https://taskmaverick.com/privacy-policy.</Clause>
          <Clause n="6.4" term="Personal Data Collection:">We care about the privacy of our users. We collect, use, and share personally identifiable information and non-personally identifiable information described in our Privacy Policy. Using the Service, you agree to the collection of such information and to have your personal data collected, used, and transferred to and processed in the United States.</Clause>
          <Clause n="6.5" term="California Consumer Privacy Act:">We comply with all applicable regulations, including the California Consumer Privacy Act (the &ldquo;CCPA&rdquo;) as well as the General Data Protection Regulation (the &ldquo;GDPR&rdquo;) when we store or use jurisdictionally applicable User&rsquo;s personal information, as long as such personal information does not enable identification of an individual. We shall exclusively have ownership of all personal information collected by us. For further information, please visit our California Privacy policy here: https://taskmaverick.com/privacy-policy-california and for our GDPR Privacy Policy here: https://taskmaverick.com/privacy-policy-gdpr.</Clause>
        </section>

        <section className="legal-section">
          <h2>7.0 Taskmaverick&rsquo;s License to You</h2>
          <Clause n="7.1" term="Customer Data:">Customer Data includes any data or material entered into the Service by the Customer, whether through our website or via the mobile application. Customers will always have all rights, titles, interests, and controls regarding the Customer Data. Subject to these Terms, Taskmaverick gives you a personal, worldwide, royalty-free, non-assignable, non-sublicensable, and non-exclusive license to use the Service. We reserve all rights not expressly granted in these Terms in the Service. We can terminate this license at any time for any reason or no reason.</Clause>
          <Clause n="7.2" term="Systems Compatibility:">We may make available Software to access the Service via a website and a mobile device. To use the Software, you must have a computer or mobile device compatible with the Service. We do not warrant that the Software will be compatible with your computer or mobile device. We give you a nonexclusive, non-transferable, revocable license to use a compiled code copy of the Software for one account on any mobile device or computer owned or leased solely by you or your Organization, for your Admin use only.</Clause>
          <Clause n="7.3" term="Software Modification:">You may not (i) modify, disassemble, decompile, or reverse engineer the Software, except to the extent that such restriction is expressly prohibited by law; (ii) rent, lease, loan, resell, sublicense, distribute, or otherwise transfer the Software to any third party or use the Software to provide time-sharing or similar services for any third party; (iii) make any copies of the Software; (iv) remove, circumvent, disable, damage, or otherwise interfere with security-related features of the Software, features that prevent or restrict use or copying of any content accessible through the Software, or features that enforce limitations on use of the Software; or (v) delete the copyright and other proprietary rights notices on the Software. You agree that we may, from time to time, issue upgraded versions of the Software and may automatically electronically upgrade the version of the Software that you are using on your mobile device. You agree to the automatic upgrading on your mobile device and agree that service terms will apply to any upgrades.</Clause>
        </section>

        <section className="legal-section">
          <h2>8.0 Third Party Components Within Our Service</h2>
          <Clause n="8.1" term="Open Source Code:">Our Service includes third-party codes and libraries that are subject to the third-party open source license terms (the &ldquo;Open Source Code&rdquo; and the &ldquo;Open Source Terms,&rdquo; respectively). Some of such Open Source Terms determine that, to the extent applicable to the respective Open Source Code licensed thereunder, such terms prevail over any conflicting license terms, including these Terms. We use our best endeavors to identify such Open Source Code within our Service; hence we encourage Users to become familiar with such Open Source Terms. Note, we use our best efforts to use only Open Source Codes that do not impose any obligation or affect the User Data or related intellectual property. These efforts apply to our Service&rsquo;s typical use that does not involve any modification, distribution, or independent use of such Open Source Code. Notwithstanding anything to the contrary, we make no warranty or indemnity hereunder concerning any Open Source Codes.</Clause>
          <Clause n="8.2" term="Third Party License:">Any third-party code that may be incorporated in the Software is covered by the applicable open source or third-party license EULA, if any, authorizing use of such code. This license is not a sale of the Software or any copy thereof. Taskmaverick or its third-party partners or suppliers retain all right, title, and interest in the Software (and any copy thereof). We reserve all rights not expressly granted under these Terms. If the Software is acquired on behalf of the United States Government, then the following provision applies: Use, duplication or disclosure of the Software by the U.S. Government is subject to restrictions outlined in these Terms and as provided in DFARS 227.7202-1(a) and 227.7202-3(a) (1995), DFARS 252.227-7013(c)(1)(ii) (OCT 1988), DFARS 252.227-7013(c) (2015), FAR 12.212(a) (1995), FAR 52.227-19, or FAR 52.227-14 (ALT III), as applicable.</Clause>
          <Clause n="8.3" term="Software Origination:">The Software originates in the United States and is subject to United States export laws and regulations. The Software may not be exported or re-exported to certain countries or those persons or entities prohibited from receiving exports from the United States. Also, the Software may be subject to the import and export laws of other countries. You agree to comply with all United States and foreign laws related to the Software and the Service use.</Clause>
        </section>

        <section className="legal-section">
          <h2>9.0 Your Content</h2>
          <Clause n="9.1" term="Content Activity:">Some areas of the Service allow you to post or upload information, text, graphics, or other material (&ldquo;Content&rdquo; or, when posted by you, &ldquo;your Content&rdquo;) and to share your Content with others. You retain ownership of your Content, but there are many things that users may do with your Content, for example, copy it, modify it, re-share it, or broadcast it. In no event shall Taskmaverick be responsible for such activity, nor shall Taskmaverick incur any liability for such actions. You understand that publishing your Content on the Service is not a substitute for registering it with the U.S. Copyright Office, the Writers Guild of America, or any other rights organization. Carefully consider what you choose to share.</Clause>
          <Clause n="9.2" term="Objectionable Material:">You agree not to post Content that (i) may create a risk of harm, loss, physical or mental injury, emotional distress, death, disability, disfigurement, or physical or mental illness to you, to any other person, or to any animal; (ii) may create a risk of any other loss or damage to any person or property; (iii) seeks to harm or exploit children by exposing them to inappropriate Content, asking for personally identifiable details or otherwise; (iv) may constitute or contribute to a crime or tort; (v) contains any information or Content that we deem to be unlawful, harmful, abusive, racially or ethnically offensive, defamatory, infringing, invasive of personal privacy or publicity rights, harassing, humiliating to other people (publicly or otherwise), libelous, threatening, profane, or otherwise objectionable; (vi) contains any information or Content that is illegal (including, without limitation, the disclosure of insider information under securities law or of another party&rsquo;s trade secrets); (vii) contains any information or Content that you do not have a right to make available under any law or under contractual or fiduciary relationships; or (viii) contains any information or Content that you know is not correct and current. You agree that any Content that you post does not and will not violate rights of any kind, including without limitation any intellectual property rights or rights of privacy. We reserve the right but are not obligated to reject and/or remove any Content that we believe, in our sole discretion, violates these provisions.</Clause>
          <Clause n="9.3" term="Ownership and License:">You retain full ownership of your Content. However, you agree to grant us a worldwide, non-exclusive, irrevocable, transferable, perpetual, royalty-free license (with the right to sublicense) to use, copy, reproduce, process, adapt, modify, publish, transmit, edit, translate, make derivatives, display, and distribute such Content in connection with providing the Service to you and other users in accordance with your settings on the Service. In providing the Service, we may modify or adapt your Content to transmit, display or distribute it over computer networks and various media. We may modify or adapt your Content and/or make changes to your Content as necessary to conform and adapt that Content to any requirements or limitations of any networks, devices, services, or media.</Clause>
          <Clause n="9.4" term="Content Oversight:">We reserve the right, but are not obligated, to remove or refuse to distribute any Content on the Service, including your Content. We also reserve the right to access, read, preserve, and disclose any information as we reasonably believe is necessary to (i) satisfy any applicable law, regulation, legal process, or governmental request; (ii) enforce the Terms, including investigation of potential violations; (iii) detect, prevent, or otherwise address fraud, security, or technical issues; (iv) respond to user support requests; or (v) protect the rights, property, or safety of Taskmaverick, its users, and the public.</Clause>
          <Clause n="9.5" term="Data Restrictions:">Customer further agrees that it shall not enter any data into the Service which is under special protection, such as data that is classified under GDPR, Article 9(1) or any other legitimate authority anywhere; (ii) which contains any health information subject to protection under the Health Insurance Portability and Accountability Act (&ldquo;HIPAA&rdquo;); and (iii) data containing any payment or banking card data subject to PCI DSS.</Clause>
        </section>

        <section className="legal-section">
          <h2>10.0 Taskmaverick Property, Copyrights, and Feedback</h2>
          <Clause n="10.1" term="Right, Title and Interest:">All right, title and interest in and to the Service (excluding Content provided by users) are and will remain the exclusive property of Taskmaverick and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries. Nothing in the Terms gives you a right to use the Taskmaverick name or any of the Taskmaverick trademarks, logos, domain names, and other distinctive brand features. Any feedback, comments, or suggestions you may provide regarding Taskmaverick or the Service is entirely voluntary. We will be free to use such feedback, comments, or suggestions as we see fit and without any obligation to you.</Clause>
          <Clause n="10.2" term="User Advertising:">Except as expressly agreed to in writing by Taskmaverick, Taskmaverick reserves the right to publicly use the User&rsquo;s name and logo for advertising that the User is a user of Taskmaverick. Taskmaverick shall not make any other claims about the User, except that the User is a user of Taskmaverick.</Clause>
          <Clause n="10.3" term="API:">Should we offer you an application programming interface (&ldquo;API&rdquo;), such API shall be governed by the Terms herein. We reserve the right at any time to change or discontinue your access to our API with or without notice and without any liability or obligation to you. Should we offer you an API, we shall do so without any warranties for its use or suitability for your purposes, systems, or Software.</Clause>
        </section>

        <section className="legal-section">
          <h2>11.0 Use of Content</h2>
          <Clause n="11.1" term="Content Veracity:">All Content in or on the Service, whether publicly posted or privately transmitted by users, is the sole responsibility of the person who originated such Content. We do not endorse, support, represent, or guarantee the completeness, truthfulness, accuracy, or reliability of any Content or communications posted via the Service or endorse any opinions expressed via the Service. We may not monitor or control the Content posted via the Service, and we cannot take responsibility for such Content. If you use or rely on any Content or materials posted via the Service or obtained by you through the Service, it is at your own risk. Under no circumstances will Taskmaverick be liable for any Content, any loss, or damage of any kind incurred due to the use of any Content in the Service. You agree that you are responsible for your use of the Service, for any Content you provide, and for any consequences thereof, including the use of your Content by other users and third parties. You understand that if you do not have the right to submit Content to the Service, doing so may subject you to liability. Taskmaverick will not be responsible or liable for any use of your Content by Taskmaverick under these Terms. You represent and warrant that you have all the rights, power, and authority necessary to grant the rights granted herein to any Content you submit, including all the required rights to upload your Content for use according to these terms and conditions.</Clause>
        </section>

        <section className="legal-section">
          <h2>12.0 Acceptable Use of Taskmaverick</h2>
          <Clause n="12.1" term="Platform Misuse:">Taskmaverick is trusted by its users, and we trust you to use our Service responsibly. You agree not to misuse the Service. For example, you must not and must not attempt to do the following things:</Clause>
          <ul className="legal-sub">
            <li>use the Service for any unlawful purposes or promotion of illegal activities;</li>
            <li>post any Content on the Service in violation of any applicable law, including intellectual property laws and right of privacy or publicity laws or any contractual obligation;</li>
            <li>impersonate others through the Service or otherwise misrepresent your affiliation with a person or entity in a manner that does or is intended to mislead, confuse, or deceive others;</li>
            <li>publish or post other people&rsquo;s private or personally identifiable information, such as credit card numbers, personal health information, street address or Social Security/National Identity numbers, without their express authorization and permission;</li>
            <li>send unsolicited communications, promotions or advertisements, or spam;</li>
            <li>publish or link to malicious Content intended to damage or disrupt another user&rsquo;s browser or computer or to compromise a user&rsquo;s privacy;</li>
            <li>access, tamper with, or use non-public areas of the Service, Taskmaverick&rsquo;s computer systems, or the technical delivery systems of Taskmaverick&rsquo;s providers;</li>
            <li>probe, scan, or test the vulnerability of any system or network or breach or circumvent any security or authentication measures;</li>
            <li>access or search the Services by any means other than our publicly supported interfaces (for example, &ldquo;scraping&rdquo;);</li>
            <li>forge any TCP/IP packet header or any part of the header information in any email or posting, or in any way use the Service to send altered, deceptive, or false source-identifying information;</li>
            <li>interfere with, or disrupt, the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the Service, or by scripting the creation of Content in such a manner as to interfere with or create an undue burden on the Service. International users agree to comply with all local laws regarding online conduct and acceptable Content. We may investigate and/or suspend your account if you violate any of the above rules. Furthermore, we reserve the right to immediately terminate your account without further notice if, in our sole and absolute judgment, you violate these Terms or abuse the use of our Service.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>13.0 Third Party Websites / Services / Partners</h2>
          <Clause n="13.1" term="Third Party Resources:">The Service or third parties within the Service could provide or facilitate links, widgets, tools, or other features that permit you to access other services, products, sites, and resources initiated by third parties (collectively, &ldquo;Third-Party Resources&rdquo;). Taskmaverick does not control such Third Party Resources or any services, products, or Content provided by or through any Third-Party Resources or the business practices of any third parties providing such Third-Party Resources. Taskmaverick does not take responsibility for and does not endorse any such Third-Party Resources or the services, products, or Content made available by them. You acknowledge that Taskmaverick is not liable or responsible for any functions, Content, legality, appropriateness, accuracy, or any other aspect of such Third-Party Resources. You further acknowledge and agree that Taskmaverick will not be liable or responsible for any loss or damage caused or allegedly caused by or in conjunction with the use of or dependence on any events, Content, goods, or services made available through Third-Party Resources. Any dealings you have with third parties found while using the Services are between you and the third party and may be subject to additional terms provided by the third party, which you agree to by using such Third-Party Resources.</Clause>
          <Clause n="13.2" term="Linked Sites:">The Content of such linked sites is provided and developed by others. You should contact the site webmaster or administrator for those linked sites if you have any concerns about such links or any content located therein. As always, you should take appropriate precautions when downloading files from all websites to protect your computer from viruses and other destructive programs. Importantly, it is vital that you take the necessary steps to determine whether accessing a Third Party Resource is suitable, including protecting your personal information and privacy in using any such Third Party Resource and complying with applicable agreements. Accessing linked sites is at your own risk. At our sole discretion, we may change the fees for any Third Party Service, including imposing a new charge on a Third Party Service that was provided for free or to discontinue without notice or justification the services of any Third Party Service.</Clause>
          <Clause n="13.3" term="Third Party Links:">THE SERVICE MAY CONTAIN LINKS TO OTHER THIRD-PARTY SITES WHICH ARE NOT UNDER THE CONTROL OF TASKMAVERICK OR ANY OTHER COVERED PARTY. AS SUCH, TASKMAVERICK AND THE NOTED COVERED PARTIES ARE NOT RESPONSIBLE FOR THE CONTENTS ON ANY LINKED SITE OR LINK CONTAINED WITHIN A LINKED SITE, OR ANY CHANGES, MODIFICATIONS, OR UPDATES TO SUCH SITES. TASKMAVERICK IS PROVIDING THESE LINKS TO YOU ONLY AS A CONVENIENCE, AND THE INCLUSION OF ANY LINK DOES NOT IMPLY THAT TASKMAVERICK OR ANY COVERED PARTY RECOMMENDS OR ASSUMES ANY RESPONSIBILITY FOR THE CONTENT FOUND ON SUCH THIRD-PARTY SITES.</Clause>
          <Clause n="13.4" term="Liability Waiver:">TO THE FULL EXTENT PERMITTED UNDER ALL APPLICABLE LAWS, THE COMPANY DISCLAIMS LIABILITY FOR ANY DIRECT OR INDIRECT CONSEQUENCES ARISING FROM THE LINKS, INFORMATION, SERVICES, PRODUCTS, AND CONTENT POSTED BY USERS, ANY ACTIONS OR INACTIONS OF USERS, AND ANY USER VIOLATIONS OF ANY APPLICABLE LAWS AND REGULATIONS.</Clause>
        </section>

        <section className="legal-section">
          <h2>14.0 Service Disruptions</h2>
          <Clause n="14.1" term="Malfunctions and Modifications:">By using our Services, you agree to absolve us of any and all liability if our Service malfunctions in total or in part. Our Services may be modified or upgraded to improve the user experience or add functionality from time to time. As a result, sometimes our Services, or certain features therein, can become inoperable or incomplete by containing bugs or suffering disruptions. IN NO EVENT SHALL OUR TOTAL AGGREGATE LIABILITY FOR SERVICE DISRUPTIONS OR INTERRUPTIONS, WHETHER PREVENTABLE OR NOT, EXCEED THE AMOUNT OF A DAILY PRORATED CREDIT BASED ON THE USER&rsquo;S SUBSCRIPTION MONTHLY FEE. TO OBTAIN A STATEMENT CREDIT, USER MUST PROVIDE TASKMAVERICK NOTICE WITHIN 48-HOURS FOLLOWING ANY CLAIMED SERVICE DISRUPTION; OTHERWISE, USER MAY NOT CLAIM ANY LOSS.</Clause>
        </section>

        <section className="legal-section">
          <h2>15.0 Copyright and DMCA Take-Down</h2>
          <Clause n="15.1" term="Submissions Removal:">If you wish us to remove any submissions from our Services for any particular reason, please notify us via email at contact@taskmaverick.com. While we do not have an obligation to remove submissions merely because of a removal request, we will evaluate all such requests. We will eliminate submissions that we decide should be taken down at our sole discretion and in accordance with these Terms of Service (including our Privacy Policy) and applicable law. If you request the removal of Content due to a copyright violation (yours), please follow the guidelines indicated in Section 16 below.</Clause>
        </section>

        <section className="legal-section">
          <h2>16.0 Violation of Copyrights / Copyright Agent</h2>
          <Clause n="16.1" term="Digital Millennium Copyright Act of 1998:">The Digital Millennium Copyright Act of 1998 (the &ldquo;DMCA&rdquo;) provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. If you are the copyright owner (or are authorized to act on behalf of the copyright owner), please notify our Copyright Agent immediately of any copyright infringement. As soon as we receive your notice of a claimed potential copyright infringement, in the appropriate form as described below, we will promptly disable or remove access to the subject materials claimed to be infringed (or the subject of infringing activity). Your notice to us must be in writing, and the notice must include the following information:</Clause>
          <ul className="legal-sub">
            <li>An explanation of the copyrighted work you believe has been infringed (or if you believe several copyrighted works may have been infringed, an indicative list);</li>
            <li>A description of the Content you believe is the subject of some infringing activity, along with enough information to allow us to find the Content;</li>
            <li>An adequate amount of information to permit us to be able to contact you, such as your full name, address, telephone or mobile number, and email address;</li>
            <li>A statement demonstrating you have a &ldquo;good faith belief&rdquo; that the alleged infringing use of the Content was not authorized by the copyright owner, the copyright owner&rsquo;s agent, or by applicable law;</li>
            <li>A statement indicating that the information you have provided is accurate; and</li>
            <li>A statement, made under penalty of perjury, affirming that you are the lawful copyright owner or are lawfully authorized to act on behalf of or represent the copyright holder.</li>
          </ul>
          <Clause n="16.2" term="Infringement:">Any such infringement notification that does not comply with the DMCA&rsquo;s requirements shall not be deemed adequate notice. It shall not be deemed to confer upon Taskmaverick actual knowledge of the circumstances or facts from which material is allegedly infringed, or acts are evident.</Clause>
        </section>

        <section className="legal-section">
          <h2>17.0 Warranty Disclaimer</h2>
          <Clause n="17.1" term="Risk of Use:">THE SERVICE IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS. USE OF THE SERVICE IS AT YOUR OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WITHOUT LIMITING THE PRECEDING, TASKMAVERICK AND ITS LICENSORS DO NOT WARRANT THAT THE CONTENT IS ACCURATE, RELIABLE OR CORRECT; THAT THE SERVICE WILL MEET YOUR REQUIREMENTS; THAT THE SERVICE WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION, UNINTERRUPTED OR SECURE; THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ANY CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DOWNLOADED AT YOUR OWN RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA THAT RESULTS FROM SUCH DOWNLOAD OR YOUR USE OF THE SERVICE. WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICE OR ANY HYPERLINKED WEBSITE OR SERVICE, AND WE WILL NOT BE A PARTY TO OR IN ANY WAY MONITOR ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.</Clause>
          <Clause n="17.2" term="Service Provision:">Also, Taskmaverick may temporarily or permanently stop providing the Service, or any features within the Service, to you or users generally and may not be able to provide you with prior notice. The Service is offered as is, where is, without any future commitment to anything by Taskmaverick other than what is published and accessible on the web or via the mobile application at the time. Taskmaverick makes no warranty that what is published and accessible will remain as such in the future.</Clause>
        </section>

        <section className="legal-section">
          <h2>18.0 Limitation of Liability</h2>
          <Clause n="18.1" term="Hold Harmless:">NOTWITHSTANDING ANYTHING IN THESE TERMS OR ELSEWHERE TO THE CONTRARY AND THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW: IN NO EVENT SHALL EITHER PARTY HERETO AND ITS AFFILIATES, SUBCONTRACTORS, AGENTS, AND VENDORS (INCLUDING THE THIRD PARTY SERVICE PROVIDERS), BE LIABLE UNDER, OR OTHERWISE IN CONNECTION WITH THESE TERMS FOR (I) ANY INDIRECT, EXEMPLARY, SPECIAL, CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES; (II) ANY LOSS OF PROFITS, COSTS, ANTICIPATED SAVINGS; (III) ANY LOSS OF, OR DAMAGE TO DATA, USE, BUSINESS, REPUTATION, REVENUE OR GOODWILL; AND/OR (IV) THE FAILURE OF SECURITY MEASURES AND PROTECTIONS, WHETHER IN CONTRACT, TORT OR UNDER ANY OTHER THEORY OF LIABILITY OR OTHERWISE, AND WHETHER OR NOT SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES IN ADVANCE, AND EVEN IF A REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</Clause>
          <Clause n="18.2" term="Breach Obligations:">EXCEPT FOR THE INDEMNITY OBLIGATIONS OF EITHER PARTY UNDER THIS AGREEMENT (INDEMNIFICATION), EITHER PARTY&rsquo;S PAYMENT OBLIGATIONS HEREUNDER FOR ANY BREACH OF ANY RELATED TERMS TO THIS AGREEMENT SHALL BE THE LESSER OF (I) THE AMOUNT OF LOSS, OR (II) THE TOTAL AMOUNT OF FEES ACTUALLY PAID BY YOU DURING THE 12 CONSECUTIVE MONTHS PRECEDING THE EVENT GIVING RISE TO SUCH LIABILITY. THIS LIMITATION OF LIABILITY IS CUMULATIVE DURING THE WHOLE DURATION OF THE RELATIONSHIP BETWEEN THE PARTIES, NOT PER INCIDENT.</Clause>
        </section>

        <section className="legal-section">
          <h2>19.0 Indemnification</h2>
          <Clause n="19.1" term="User Consent:">You agree to defend, indemnify, and hold the Company, including its officers, directors, employees, agents, and licensors, harmless from and against any demands, claims, actions, liabilities, and settlements including, without any limitation, any associated reasonable legal and accounting fees, interest or penalties resulting from, or alleged to result from, your violation of this Agreement.</Clause>
          <Clause n="19.2" term="Admin Consent:">Admin and/or User on behalf of itself and its agents, officers, directors, employees or affiliates shall defend and indemnify and hold Taskmaverick and its affiliates, shareholders, employees, agents, and subcontractors harmless against all claims, suits, losses, damages, liabilities, costs, and expenses including reasonable legal costs and fees arising out of, resulting from or relating to: (a) any breach of a representation or warranty made by Admin or User herein; (b) Admin or User&rsquo;s failure to comply with any applicable laws or regulations including but not limited to the Export Control and Sanctions Rules; Customer Data, including the use of Customer Data by Taskmaverick and/or any of its subcontractors, if such infringes or violates any third party&rsquo;s rights, including, without limitation, intellectual property, privacy and/or publicity rights, (c) any alleged infringement or misappropriation of any intellectual property rights of any third party based on or related to the Service modifications not made by Taskmaverick, and/or (d) Admin or User&rsquo;s breach of this Agreement or applicable laws.</Clause>
        </section>

        <section className="legal-section">
          <h2>20.0 Compliance With All Laws</h2>
          <Clause n="20.1" term="Access, Transfer and Use of Information:">You agree that your use of our Service will comply with all relevant and applicable laws and regulations, which shall include but not be limited to U.S. export control laws and executive orders. The information provided on and through this Site or through our Service may be export-controlled technology and subject to the export control restrictions of the United States. YOU MUST VERIFY AND COMPLY WITH ALL APPLICABLE LAWS AND REGULATIONS OF THE UNITED STATES PERTAINING TO ANY POTENTIAL ACCESS, TRANSFER, AND USE OF ANY INFORMATION HEREIN WHICH MAY BE &ldquo;EXPORT-CONTROLLED&rdquo; AS DEFINED BY LAW. This Site may not be accessed or used by any national of certain countries or groups against which the United States has instituted sanctions (including Cuba, Iran, North Korea, Sudan, and Syria); especially Designated Nationals, and other proscribed entities and persons who are listed on the Denied Parties list. Due to technical uncertainties preventing verification of the identity and ultimate point of access by any person attempting to access or use the Site, including our Service, your access of the Site, including the presentment of any authorized User ID and password, constitutes your express representation that (1) the person attempting access thereunder is not a national of any such sanctioned country or group or a Specially Designated National, and (2) is not included on such Denied Parties list, and (3) that, if an Authorized User, you have not disclosed or provided such password and user ID to any such person for use under your registration. Users shall be fully liable and subject to prosecution to the full extent of the law for any violations of this paragraph, and SUCH USER HEREBY AGREES TO DEFEND, INDEMNIFY AND HOLD TASKMAVERICK HARMLESS FROM AND AGAINST ANY AND ALL SUCH DAMAGES AND LIABILITY.</Clause>
        </section>

        <section className="legal-section">
          <h2>21.0 Governing Language</h2>
          <Clause n="21.1">These Terms of Service are drafted, executed, and presented originally in the English language. In the event of any conflict, contradiction, discrepancy, or inconsistency between the English version and any translated version of these Terms, the English language version shall control and prevail in all respects. All disputes, legal proceedings, and communications arising under this Agreement shall be conducted exclusively in English.</Clause>
        </section>

        <section className="legal-section">
          <h2>22.0 Our Right to Change, Modify or Discontinue the Site and/or Services</h2>
          <Clause n="22.1" term="Service Modifications:">At times, and without prior notice to you, we may expand, change, modify, and improve our Services. At any time, we may also discontinue operating part or all of our Services or selectively deactivate certain features and functions of our Services. Your use of the Service does not entitle you to the continued provision or availability of the Service. Any modification or elimination of the Service or any particular features or functions will be conducted in our sole and outright discretion and without an ongoing obligation or liability to you. Taskmaverick shall not be liable to you or any third party for any suspension, modification, or discontinuance of our Services.</Clause>
          <Clause n="22.2" term="Service Changes:">TASKMAVERICK MAY MAKE CHANGES TO THE SERVICE, SERVICES ON THE WEB SITE, MOBILE APPLICATION, INFORMATION, SOFTWARE, DOCUMENTS, PUBLICATIONS, PRICES, TECHNICAL SPECIFICATIONS, PRODUCT OFFERINGS, AND ANY OTHER INFORMATION AND MATERIALS AT ANY TIME AND WITHOUT NOTICE.</Clause>
        </section>

        <section className="legal-section">
          <h2>23.0 Choice of Law, Jurisdiction, and Venue</h2>
          <Clause n="23.1" term="Legal Proceedings:">This Agreement between you and Taskmaverick, and your associated relationship, shall be governed, controlled by, and construed in accordance with the federal laws of the United States of America and the laws of the State of California, within the United States of America, excluding conflict of law&rsquo;s provisions that would indicate the application of the laws from another jurisdiction. Any legal action or proceeding relating to your access to, or use of, this Service or these terms of use shall be instituted only in a state or federal court located in Los Angeles County, California, United States of America. You and Taskmaverick irrevocably agree to accept the jurisdiction of such courts. You expressly and unconditionally waive any improper venue claim and any claim that said courts are an inconvenient forum. If the courts in the country where you reside should decide that the provisions or conditions of this paragraph are unenforceable, then you agree and consent to submit to binding arbitration exclusively.</Clause>
        </section>

        <section className="legal-section">
          <h2>24.0 Dispute Resolution</h2>
          <Clause n="24.1" term="Arbitration and Mediation:">The parties will attempt in good faith to resolve through negotiation any dispute, claim, or controversy arising out of or relating to these Terms of Service or any matter relating in any way to your use of the Service. If the dispute, claim, or these negotiations do not resolve the controversy, the matter will be submitted to Judicial Arbitration and Mediation Services, Inc. (a.k.a. &ldquo;JAMS&rdquo;), or its successor, for mediation, and if the matter is not resolved through mediation, then it shall be submitted to JAMS, or its successor, for final and binding arbitration. Nonetheless, legal action taken by Taskmaverick to recover damages for or obtain an injunction relating to our Service, website operations, or intellectual property shall not be submitted to arbitration or mediation except as otherwise agreed in writing by Taskmaverick. Also, either you or Taskmaverick may seek any preliminary or interim relief from a court of competent jurisdiction in the State of California, United States of America, necessary to protect the rights or property of you or Taskmaverick pending the completion of arbitration. Either party may commence the arbitration process concerning the matters submitted to mediation by filing the appropriate written demand for arbitration at any time following an initial mediation session or forty-five (45) days after the filing date of the written request for mediation, whichever happens first. The arbitration will be conducted in accordance with the provisions of JAMS&rsquo; Streamlined Arbitration Rules and Procedures in effect at the time of filing of the demand for arbitration. The parties covenant that they will participate in the arbitration in good faith and share equally in its costs. Any court of competent jurisdiction may enforce the provisions of this paragraph. The party seeking enforcement shall be entitled to an award of all costs, fees, and expenses, including attorneys&rsquo; fees, to be paid by the party against whom enforcement is ordered.</Clause>
        </section>

        <section className="legal-section">
          <h2>25.0 Class Action</h2>
          <Clause n="25.1" term="Claims:">With respect to all persons and entities, regardless of whether they have obtained or used our Service for personal, commercial, or other purposes, all claims must be brought in the parties&rsquo; individual capacity and not as a plaintiff or class member in any purported class action, collective action, private attorney general action or other representative proceedings. This waiver applies to class arbitration, and unless we agree otherwise, the arbitrator may not consolidate more than one person&rsquo;s claims.</Clause>
        </section>

        <section className="legal-section">
          <h2>26.0 General Term Disclosures, Other</h2>
          <Clause n="26.1" term="Definitions:">As used herein, the term &ldquo;including&rdquo; means &ldquo;including, but not limited to.&rdquo; Also, section headings are for limited reference purposes only and in no way limit, construe, define, or describe the scope or extent of such section.</Clause>
          <Clause n="26.2" term="Assignment:">These Terms, and any and all rights and obligations hereunder, may not be transferred or assigned by you without our written approval, provided that you may assign these Terms to your successor entity or person, resulting from a merger, acquisition, or sale of all or substantially all of your assets or voting rights, except for an assignment to a competitor of Taskmaverick. You hereby agree that all respective assignees shall agree to assume all of your obligations under these Terms in any assignment. We may assign our rights and/or obligations hereunder and/or transfer ownership rights and title in the Service to a third party without your consent or prior notice. Subject to the preceding conditions, these Terms shall bind and inure to the parties&rsquo; benefit, their respective successors, and permitted assigns. Any assignment not authorized under this Section shall be null and void.</Clause>
          <Clause n="26.3" term="No Waiver:">Any failure by us to require performance, at any time, of any condition or provision of this Agreement or to exercise any right provided for herein shall not be deemed a waiver of such provision or such right.</Clause>
          <Clause n="26.4" term="Severability:">If any provision specified herein is held to be unenforceable or invalid by a court of competent jurisdiction, such unenforceability or invalidity shall not affect the remaining provisions&rsquo; enforceability or validity. Importantly, the remaining provisions of these Terms of Service shall hereby remain in full force and effect.</Clause>
          <Clause n="26.5" term="Agreement Scope:">These Terms of Service, as described herein, encompasses the entire Agreement and understanding between us and, as such, supersede all prior agreements and understandings between you and Taskmaverick as it pertains to the subject matter hereof.</Clause>
        </section>

        <section className="legal-section">
          <h2>27.0 Changes to Our Terms of Use and Our Separate Privacy Policy</h2>
          <Clause n="27.1" term="Updates:">We unequivocally reserve the right to modify or update these Terms of Service and our separate Privacy Policy at any time, without prior notice, by posting the revised version of these Terms of Service and Privacy Policy behind a link marked &ldquo;Terms of Service&rdquo; or &ldquo;Privacy Policy,&rdquo; on our website, or within our mobile application. When we change the Terms of Service or our Privacy Policy, we will update the Effective Date on the policy page. Your continued use of our Services after we have posted the revised Terms of Service or Privacy Policy constitutes your agreement to be bound by the revised Terms of Service or our privacy practices.</Clause>
          <Clause n="27.2" term="Notice:">We shall use the contact details that we have in our records to provide you with notices, subject to this Section. Our contact details for any notices are detailed below. You acknowledge notices that we provide you, in connection with these Terms and/or as otherwise related to the Service, shall be provided as follows: via the Service, including by posting on our Sites or posting in your account, or in-app notification, or via email. You further acknowledge that an electronic notification satisfies any applicable legal notification requirements, including that such notification will be in writing. Any notice to you will be deemed given upon receipt. Notices to us shall be provided as follows:</Clause>
          <div className="legal-contact">
            <p><b>Attention:</b> General Manager</p>
            <p>
              Via email to:<br />
              <a href="mailto:contact@taskmaverick.com">contact@taskmaverick.com</a>
            </p>
            <p>
              Via certified mail to:<br />
              240 North Beverly Drive, Penthouse<br />
              Beverly Hills, CA 90210
            </p>
          </div>
        </section>
      </main>
      <SiteFooter />
      </SmoothScroll>
    </div>
  );
}
