// What the Assets Library can find a clip by: the things you can see in the
// animations, by the product's names, and the other words people use for them.
// (Kept apart from lib/assetsLibrary.mjs so the page's search needs none of the
// story code.)
// Things you can see in the animations -> other words people use for them.
export const ELEMENTS = {
  'Mission chip': ['mission card', 'card', 'chip', 'mission'],
  'Mission details': ['opened mission', 'detail view', 'mission screen', 'mission'],
  'Checklist': ['check list', 'checkpoints', 'questions', 'mission type'],
  'Timer': ['pill', 'age', 'clock', 'time posted', 'countdown'],
  'Timer color': ['green', 'orange', 'red', 'aging', 'urgency', 'color change'],
  'Execution timer': ['execution time', 'duration', 'stopwatch', 'time spent'],
  'Performer': ['who performed', 'person', 'name', 'employee', 'worker', 'assignee', 'claimer'],
  'Points': ['reward', 'score', 'motivation'],
  'Schedule': ['recurring', 'daily', 'weekly', 'monthly', 'calendar'],
  'Priority order': ['priority', 'critical', 'urgent', 'sorted', 'top of the list'],
  'Open mission': ['open', 'posted', 'available'],
  'Claimed mission': ['claimed', 'claim', 'in progress', 'taken'],
  'Closed mission': ['closed', 'close', 'done', 'finished', 'completed'],
  'Alert': ['warning', 'risk', 'hazard', 'notice'],
  'Instructions': ['standards', 'reminder', 'description', 'how to'],
  'Link': ['url', 'resource', 'external', 'website', 'outside resource'],
  'Translate button': ['language', 'spanish', 'english', 'translation', 'es', 'en'],
  'Yes / No answers': ['answer', 'options', 'checkbox', 'true false'],
  'Micro-training': ['lesson', 'learning', 'training', 'course'],
  'Training video': ['lesson video', 'video player', 'onboarding'],
  'Quiz': ['test', 'questions', 'true false'],
  'Photo': ['picture', 'image', 'proof', 'evidence'],
  'Video': ['recording', 'clip', 'proof', 'evidence'],
  'Proof': ['evidence', 'documentation', 'attachment'],
  'Rating': ['rate', 'stars', 'score', 'review', 'feedback'],
  'Self-rating': ['rate yourself', 'accountability', 'slider'],
  'Peer rating': ['crowdsource', 'rated by', 'quality control'],
  'Tablet': ['shared device', 'device', 'mobile device'],
  'Team board': ['board', 'columns', 'open claimed closed'],
  'Personal board': ['phone', 'mobile', 'my missions', 'individual'],
  'Menu': ['navigation', 'drawer', 'hamburger'],
  'Knowledge base': ['library', 'documents', 'information', 'wiki'],
  'Business proofs': ['gallery', 'evidence', 'photos', 'documented'],
  'Web report': ['dashboard', 'usage report', 'reports', 'web app', 'browser'],
  'Gallery view': ['photo grid', 'thumbnails', 'gallery'],
  'Date & time': ['timestamp', 'date', 'when', 'captured'],
  'Personal code': ['pin', 'code', 'keypad', 'passcode', 'login'],
  'Avatar': ['team member', 'person', 'face', 'profile'],
  'Hand': ['cursor', 'pointer', 'click', 'tap', 'pointing', 'finger', 'yellow hand'],
  'Speech bubble': ['chat', 'message', 'caption', 'teardrop', 'words', 'text'],
  'Spotlight': ['dim', 'dark', 'highlight', 'circle', 'callout'],
  'Title card': ['words only', 'text only', 'intro', 'opening', 'outro'],
};
// Searches worth suggesting under the search box.
export const SUGGESTIONS = ['Alert', 'Mission details', 'Mission chip', 'Timer', 'Execution timer', 'Performer', 'Personal code', 'Rating', 'Photo', 'Web report'];
