// Generated by scripts/generate-tts.mjs. Durations include encoder padding.
export const DEMO_AUDIO = {
  "title-sub1": {
    "duration": 4.023,
    "hash": "4c3ac65b88e010fa",
    "voice": "O4Sq7yQC1fd484Lr500R"
  },
  "title-sub2": {
    "duration": 3.632,
    "hash": "dcb0313b80d7e6e4",
    "voice": "O4Sq7yQC1fd484Lr500R"
  },
  "cue-personal": {
    "duration": 3.788,
    "hash": "a2247d708ac39e49",
    "voice": "O4Sq7yQC1fd484Lr500R"
  },
  "cue-team": {
    "duration": 4.285,
    "hash": "281363d1868e8139",
    "voice": "O4Sq7yQC1fd484Lr500R"
  },
  "device-sharing": {
    "duration": 1.098,
    "hash": "cfd891fdf043ee55",
    "voice": "O4Sq7yQC1fd484Lr500R"
  },
  "msg-mid": {
    "duration": 3.814,
    "hash": "f5ca6d95d9f63ad9",
    "voice": "O4Sq7yQC1fd484Lr500R"
  },
  "cue-claim": {
    "duration": 3.214,
    "hash": "e2d1c3ae13271627",
    "voice": "O4Sq7yQC1fd484Lr500R"
  },
  "cue-close": {
    "duration": 3.867,
    "hash": "61207e5896e80f0c",
    "voice": "O4Sq7yQC1fd484Lr500R"
  },
  "cue-shared": {
    "duration": 4.52,
    "hash": "230c643c05d260d6",
    "voice": "O4Sq7yQC1fd484Lr500R"
  },
  "msg-end": {
    "duration": 3.083,
    "hash": "d1407cca469dd360",
    "voice": "O4Sq7yQC1fd484Lr500R"
  }
};
