// Generate ElevenLabs narration audio for the Automation demo.
//
//   node scripts/generate-tts.mjs          # missing or changed voice/script lines
//   node scripts/generate-tts.mjs --force  # regenerate everything
//
// Reads ELEVENLABS_API_KEY from the environment or .env.local (gitignored).
// Writes one mp3 per spoken line and measured durations into lib/demoAudio.mjs.
// Silent title cards are never submitted to ElevenLabs. The key is used
// ONLY here — it never ships to the browser (the client just plays the mp3s).

import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { mp3Duration } from './mp3-duration.mjs';

import { DEMO_SCRIPT, TTS_VOICE_ID, TTS_MODEL_ID } from '../lib/demoScript.mjs';
import { DEMO_AUDIO } from '../lib/demoAudio.mjs';

const ROOT = process.cwd();
const OUT = path.join(ROOT, 'public', 'tts');
const FORCE = process.argv.includes('--force');

// Minimal .env.local loader (no dotenv dependency).
async function loadKey() {
  if (process.env.ELEVENLABS_API_KEY) return process.env.ELEVENLABS_API_KEY;
  try {
    const env = await fs.readFile(path.join(ROOT, '.env.local'), 'utf8');
    for (const line of env.split('\n')) {
      const m = line.match(/^\s*ELEVENLABS_API_KEY\s*=\s*(.+?)\s*$/);
      if (m) return m[1].replace(/^["']|["']$/g, '');
    }
  } catch {
    /* no .env.local */
  }
  return null;
}

async function main() {
  const key = await loadKey();
  if (!key) {
    console.error('Missing ELEVENLABS_API_KEY (set it in the environment or .env.local).');
    process.exit(1);
  }
  await fs.mkdir(OUT, { recursive: true });

  const metadata = { ...DEMO_AUDIO };
  for (const n of DEMO_SCRIPT.filter(line => line.text)) {
    const hash = createHash('sha256').update(JSON.stringify([TTS_VOICE_ID, TTS_MODEL_ID, n.text, .5, .75])).digest('hex').slice(0, 16);
    const file = path.join(OUT, `${n.id}.mp3`);
    if (!FORCE && metadata[n.id]?.hash === hash) {
      try {
        await fs.access(file);
        console.log(`skip  ${n.id} (exists)`);
        continue;
      } catch {
        /* not generated yet */
      }
    }
    const res = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${TTS_VOICE_ID}`, {
      method: 'POST',
      headers: { 'xi-api-key': key, 'content-type': 'application/json', accept: 'audio/mpeg' },
      body: JSON.stringify({
        text: n.text,
        model_id: TTS_MODEL_ID,
        voice_settings: { stability: 0.5, similarity_boost: 0.75 },
      }),
    });
    if (!res.ok) {
      console.error(`FAIL  ${n.id}: ${res.status} ${await res.text()}`);
      process.exit(1);
    }
    const buf = Buffer.from(await res.arrayBuffer());
    const duration = mp3Duration(buf);
    await fs.writeFile(file, buf);
    metadata[n.id] = { duration, hash, voice: TTS_VOICE_ID };
    await fs.writeFile(path.join(ROOT, 'lib', 'demoAudio.mjs'), `// Generated by scripts/generate-tts.mjs. Durations include encoder padding.\nexport const DEMO_AUDIO = ${JSON.stringify(metadata, null, 2)};\n`);
    console.log(`wrote ${n.id}.mp3 (${duration}s, ${buf.length} bytes)`);
  }
  console.log('Done.');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
