'use client';
import { useEffect, useRef, useState } from 'react';
import { QUALITY_ASSETS } from '@/lib/qualityAssets';
import QualityAssetScreen from './QualityAssetScreen';
import './QualityAssets.css';

const referenceUrl=file=>`/quality-assets/reference/${file}`;
export default function QualityAssetLibrary({references}) {
  const [selected,setSelected]=useState('opened'),[device,setDevice]=useState('tablet'),[category,setCategory]=useState('All assets'),[query,setQuery]=useState(''),[view,setView]=useState('assets'),[state,setState]=useState(0),[revision,setRevision]=useState(0),[media,setMedia]=useState({}),[message,setMessage]=useState(''),[reference,setReference]=useState(null);
  const objectUrls=useRef({});
  useEffect(()=>()=>Object.values(objectUrls.current).forEach(URL.revokeObjectURL),[]);
  const asset=QUALITY_ASSETS.find(a=>a.id===selected);
  const groups=['All assets',...new Set(QUALITY_ASSETS.map(a=>a.group))];
  const filtered=QUALITY_ASSETS.filter(a=>(category==='All assets'||a.group===category)&&`${a.title} ${a.note} ${a.shot}`.toLowerCase().includes(query.toLowerCase()));
  const related=(asset.refs||[]).map(ref=>`${ref}.png`).filter(file=>references.includes(file));
  const cleanUrl=`/quality-assets/preview?asset=${asset.id}&device=${device}&state=${state}`;
  function select(item){setSelected(item.id);setState(0);setReference(null);}
  function setFile(event,type){const file=event.target.files?.[0];if(!file)return; if(objectUrls.current[type])URL.revokeObjectURL(objectUrls.current[type]);const url=URL.createObjectURL(file);objectUrls.current[type]=url;setMedia(value=>({...value,[type]:url}));setMessage(`${file.name} added for this preview session.`);}
  function downloadManifest(){const blob=new Blob([JSON.stringify({title:'Improved Quality',devices:{mobile:[390,844],tablet:[1080,808]},assets:QUALITY_ASSETS,references:references.map(file=>({file,url:referenceUrl(file),source:'https://mobile.taskmaverick.com/',captured:'2026-09-23'}))},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='improved-quality-assets.json';link.click();URL.revokeObjectURL(url);}
  return <main className="qal"><header className="qal-header"><a href="/phone" className="qal-brand"><img src="/logo.svg" alt="Taskmaverick"/></a><span className="qal-header-divider"/><span>Video production <span className="qal-muted">/ Asset library</span></span><a className="qal-link" href="/phone">Open phone workspace ↗</a></header>
    <section className="qal-intro"><div><div className="qal-eyebrow">IMPROVED QUALITY · DEMO 02</div><h1>Every screen. One library.</h1><p>Browse the building blocks for the next demo. Preview, compare, and compose.</p></div><button className="qal-button" onClick={downloadManifest}>↓ Asset manifest</button></section>
    <div className="qal-stats"><span><b>{QUALITY_ASSETS.length}</b> reusable screens</span><span><b>2</b> device layouts</span><span><b>{references.length}</b> live references</span><span className="qal-preserved"><i/> Original mission chips & icons</span></div>
    <nav className="qal-tabs" aria-label="Library views"><button className={view==='assets'?'is-active':''} onClick={()=>setView('assets')}>Screen library <span>{QUALITY_ASSETS.length}</span></button><button className={view==='references'?'is-active':''} onClick={()=>setView('references')}>Live app captures <span>{references.length}</span></button><button className={view==='media'?'is-active':''} onClick={()=>setView('media')}>Media & icons</button></nav>
    {view==='assets'&&<div className="qal-workspace"><aside className="qal-catalog"><label className="qal-search"><span>⌕</span><input aria-label="Search assets" placeholder="Find a screen or shot…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="qal-filters">{groups.map(group=><button key={group} className={category===group?'is-active':''} onClick={()=>setCategory(group)}>{group}</button>)}</div><div className="qal-list">{filtered.map((item,i)=><button key={item.id} className={`qal-item ${selected===item.id?'is-selected':''}`} onClick={()=>select(item)}><span className="qal-item-icon"><img src={`/board-icons/${item.icon}.svg`} alt=""/></span><span className="qal-item-label"><b>{item.title}</b><small>{item.group} · Shot {item.shot}</small></span><span className={`qal-dot ${item.kind==='new'?'is-new':''}`} title={item.kind==='new'?'Added demo surface':'Existing component'}/></button>)}{!filtered.length&&<p className="qal-empty">No assets match this search.</p>}</div><div className="qal-legend"><span><i className="qal-dot"/> Existing component</span><span><i className="qal-dot is-new"/> Added demo surface</span></div></aside>
      <section className="qal-inspector"><div className="qal-inspector-head"><div><span className="qal-eyebrow">{asset.group} / SHOT {asset.shot}</span><h2>{asset.title}</h2></div><div className="qal-segment">{['mobile','tablet'].map(value=><button key={value} aria-pressed={device===value} onClick={()=>{setDevice(value);setReference(null);}}>{value==='mobile'?'Mobile':'Tablet'}</button>)}</div></div><div className="qal-preview-tools"><div className="qal-states">{asset.states?.map((label,index)=><button key={label} aria-pressed={index===state} onClick={()=>{setState(index);setReference(null);setRevision(n=>n+1);}}>{label}</button>)||<span>Ready to preview · Timers frozen</span>}</div><button className="qal-text-button" onClick={()=>{setState(0);setRevision(n=>n+1);}}>Reset</button></div>
        <div className={`qal-stage ${device==='mobile'?'qal-stage--mobile':''}`}><div className={`qal-device qal-device--${device}`}>{reference?<img className="qal-reference-preview" src={referenceUrl(reference)} alt={reference.replaceAll('-',' ')}/>:<div className="qal-device-canvas"><QualityAssetScreen key={`${asset.id}-${device}-${revision}`} asset={asset} device={device} initialState={state} media={media} onStateChange={setState}/></div>}</div></div>
        <div className="qal-preview-bottom"><span>{reference?'Live app screenshot':`${device==='mobile'?'390 × 844':'1080 × 808'} · Interactive demo asset`}</span><a href={cleanUrl} target="_blank" rel="noreferrer">Open clean preview ↗</a></div>
        <div className="qal-notes"><div><span className={`qal-badge ${asset.kind==='new'?'is-new':''}`}>{asset.kind==='new'?'Added demo surface':'Reused component'}</span><p>{asset.note}</p>{asset.needsMedia&&<p className="qal-media-note">{media.photo||media.video?'Session media is active in this library preview.':'Evidence frames are ready; the actual shelving photo and broken-item video are still needed.'}</p>}</div><div className="qal-reference-links"><b>Live reference</b>{related.length?related.map(file=><button key={file} onClick={()=>setReference(reference===file?null:file)} className={reference===file?'is-active':''}>{file.startsWith('tablet')?'Tablet':'Mobile'} capture ↗</button>):<span>Not captured for this screen yet</span>}{reference&&<button onClick={()=>setReference(null)}>Back to editable asset</button>}</div></div>
      </section></div>}
    {view==='references'&&<section className="qal-reference-section"><div className="qal-section-copy"><h2>Captured from the product</h2><p>Original screenshots from mobile.taskmaverick.com. Open or download any reference at its captured resolution.</p></div><div className="qal-reference-grid">{references.map(file=><article key={file}><a href={referenceUrl(file)} target="_blank" rel="noreferrer"><img loading="lazy" src={referenceUrl(file)} alt={file.replace('.png','').replaceAll('-',' ')}/></a><div><b>{file.replace('.png','').replaceAll('-',' ')}</b><a href={referenceUrl(file)} download={file}>↓ PNG</a></div></article>)}</div></section>}
    {view==='media'&&<section className="qal-media-section"><div className="qal-section-copy"><h2>Use what we already have</h2><p>The existing video, mission logo, media badges, and navigation icons are reused unchanged.</p></div><div className="qal-media-grid"><article><video controls preload="metadata" src="/videos/training%20video%201.mp4"/><h3>Micro-training video</h3><a href="/videos/training%20video%201.mp4" download>Download original MP4 ↓</a></article><article><h3>Evidence for this demo</h3><p>Add the shelving photo and broken-item video to preview them throughout the evidence screens. Files stay in this browser session.</p><label className="qal-upload">Choose shelving photo<input type="file" accept="image/*" onChange={e=>setFile(e,'photo')}/></label><label className="qal-upload">Choose condition video<input type="file" accept="video/*" onChange={e=>setFile(e,'video')}/></label><small>Clean-preview links use the empty media frames; session uploads appear in the library only.</small></article></div><div className="qal-icon-grid">{['media-video','media-quiz','media-image','media-audio'].map(name=><a key={name} href={`/mission-icons/${name}.svg`} download><img src={`/mission-icons/${name}.svg`} alt={name}/><span>{name.replace('media-','')}</span></a>)}{['team','person','like','image','book','file','calendar','clock'].map(name=><a key={name} href={`/board-icons/${name}.svg`} download><img src={`/board-icons/${name}.svg`} alt={name}/><span>{name}</span></a>)}</div></section>}
    <p className="qal-announcement" role="status">{message}</p><footer className="qal-footer">Improved Quality · Production asset library<span>Live references + reusable demo components</span></footer>
  </main>;
}
