'use client';

import { useEffect, useState } from 'react';
import InteractiveMissionBoard from '../InteractiveMissionBoard';
import { OpenedMission } from '../OpenedMission';
import PhoneShell, { IconBack, IconMenu } from '../PhoneShell';
import MissionChip from '../MissionChip';
import { BoardMenu, MenuIcon } from '../BoardNavigation';
import { Stars } from '../quality/parts';
import { checklist } from '@/lib/openedMissions';
import { REFERENCE_MISSIONS } from '@/lib/referenceMissions';
import { mediaTrainingMission } from '../MediaTraining';
import './QualityAssets.css';

const mission = {...checklist, title:'Closing Checklist', date:'09-23-26',time:'04:10 PM',pillTime:'00:07:40',description:'Check the shelves and work areas against the closing standard.',claimedWho:'Anna F. - Staff'};
const board = REFERENCE_MISSIONS.map(m=>({...m, pillTime:'00:07:40'}));
const records = [
  {person:'Anna F.',title:'Closing Checklist',checkpoint:'Shelving standard',date:'09-23-26',time:'04:12:08 PM',kind:'Photo'},
  {person:'Ben R.',title:'Equipment Inspection',checkpoint:'Report damaged equipment',date:'09-23-26',time:'03:48:22 PM',kind:'Video'},
  {person:'Carla M.',title:'Closing Checklist',checkpoint:'Shelving standard',date:'09-22-26',time:'04:16:31 PM',kind:'Photo'},
  {person:'Anna F.',title:'Equipment Inspection',checkpoint:'Report damaged equipment',date:'09-22-26',time:'03:40:12 PM',kind:'Video'},
];
function Head({title='Mission Details',onBack,onMenu}) { return <header className="qa-product-head"><button aria-label="Back" onClick={onBack}><IconBack/></button><b>{title}</b><button aria-label="Menu" onClick={onMenu}><IconMenu/></button></header>; }
function Summary(){return <div className="qa-summary"><div><img src="/mission-logo.png" alt=""/>Checklist<span className="chip-pill">00:07:40</span></div><h3>Closing Checklist</h3><p>Kitchen / 1</p><footer><span>Anna F. - Staff</span><span>09-23-26 · 04:10 PM</span></footer></div>;}
function MissingMedia({video=false}) {return <div className="qa-empty-media"><img src={`/mission-icons/media-${video?'video':'image'}.svg`} alt=""/><span>{video?'Video evidence':'Photo evidence'}</span></div>;}
function Evidence({record,media,onOpen,emphasis}) {const source=record.kind==='Video'?media.video:media.photo;return <article className="qa-evidence"><header><span className="qa-avatar">{record.person[0]}</span><div><b className={emphasis==='performed-by'?'qa-emphasis':''}>{record.person}</b><small>{record.title}</small></div><span className="qa-media-kind">{record.kind}</span></header><button className="qa-evidence-picture" onClick={onOpen} aria-label={`Open ${record.checkpoint}`}>{source?(record.kind==='Video'?<video src={source} muted preload="metadata"/>:<img src={source} alt={record.checkpoint}/>):<MissingMedia video={record.kind==='Video'}/>}</button><div className="qa-evidence-caption"><b>{record.checkpoint}</b><span className={emphasis==='timestamp'?'qa-emphasis':''}>{record.date} · {record.time}</span></div></article>;}

function Surface({asset,index,setIndex,media}) {
  const [answer,setAnswer]=useState(null),[rating,setRating]=useState(0),[filter,setFilter]=useState('All media'),[opened,setOpened]=useState(null),[menu,setMenu]=useState(asset.id==='menu');
  const id=asset.id;
  if(['opened','checklist','training','translate'].includes(id)) {
    const translated=id==='translate'&&index===1;
    const item=id==='training'?mediaTrainingMission:translated?{...mission,title:'Lista de cierre',description:'Revise los estantes y las áreas de trabajo según el estándar de cierre.',notice:'No contamine. Use las herramientas designadas para cada superficie.',sectionTitle:'Lista de verificación',groups:mission.groups.map(g=>({...g,title:g.title==='Shelf'?'Estante':g.title==='Shelf 2'?'Estante 2':g.title==='Warehouse'?'Almacén':'Total',items:g.items?.map(i=>({...i,label:i.label==='Plates'?'Platos':i.label==='Cups'?'Tazas':'Platos'}))}))}:mission;
    return <div className="qa-detail mi-detail-inner">{id==='translate'&&<button className="qa-language" onClick={()=>setIndex(index?0:1)}>{translated?'EN · English':'ES · Español'}</button>}<OpenedMission mission={item} state={id==='opened'?'open':'claimed'} showExec={id!=='opened'} showStatusBar={false} execTime="00:02:20"/></div>;
  }
  if(id==='steps')return <div className="qa-product"><Head/><Summary/><div className="qa-product-body"><div className="qa-step-heading"><span>Checklist</span><b>{Math.min(index,3)}/3</b></div>{['Are the shelves clean and organized?','Are all items stored in the designated area?','Is the work area ready for the next shift?'].map((label,i)=><section className={`qa-step ${i===index?'is-current':''}`} key={label}><b>{i+1}. {label}</b><div>{['Yes','No','N/A'].map(choice=><button key={choice} className={i<index&&choice==='Yes'?'is-selected':''} disabled={i>index} onClick={()=>choice==='Yes'&&setIndex(Math.min(3,index+1))}>{i<index&&choice==='Yes'?'✓ ':''}{choice}</button>)}</div></section>)}<section className={`qa-step ${index===3?'is-current':''}`}><b>4. Review the closing standard</b><div className="qa-media-row"><img src="/mission-icons/media-video.svg" alt=""/>Micro-training · 00:30</div>{index===3&&<video src="/videos/training%20video%201.mp4" controls playsInline preload="metadata"/>}</section></div></div>;
  if(id==='lesson')return <div className="qa-product"><Head/><div className="qa-product-body"><div className="qa-step-heading"><span>4/4 · Closing standard</span><img src={`/mission-icons/media-${index?'audio':'video'}.svg`} alt=""/></div>{index===0?<video className="qa-video-player" src="/videos/training%20video%201.mp4" controls playsInline preload="metadata"/>:<div className="qa-lesson-text"><h3>Proper Cleaning</h3><p>Start by wiping the exterior with a clean, damp cloth to remove stains and spills. Purge the steam wand, then wipe it down. Clean the portafilter and basket, and empty and rinse the drip tray.</p></div>}<p>Review the standard before continuing to the inspection.</p></div></div>;
  if(id==='quiz')return <div className="qa-product"><Head/><Summary/><div className="qa-product-body"><div className="qa-step-heading"><span>2/2</span><b>Quiz</b></div><h3>1. What is the first step in cleaning the coffee machine?</h3>{['Backflush the machine','Wipe the exterior','Descale the machine','Remove the drip tray'].map((label,i)=><label className="qa-answer" key={label}><input name="quality-answer" type="radio" checked={(index>0?1:answer)===i} onChange={()=>{setAnswer(i);setIndex(0);}}/>{label}</label>)}{index===2&&<div className="qa-success">✓ Correct answer · Quiz passed</div>}</div><footer className="qa-product-footer"><button disabled={answer==null&&index===0} onClick={()=>{if(answer===1||index>0)setIndex(2);else setAnswer(null);}}>{index===2?'Continue':'Submit answer'}</button></footer></div>;
  if(['photo','video'].includes(id)) {const video=id==='video';const src=media[id];return <div className="qa-product"><Head title={index===2?(video?'Video':'Photo'):'Mission Details'} onBack={()=>setIndex(0)}/>{index!==2&&<Summary/>}<div className="qa-product-body"><h3>{video?'6. Report any damaged equipment':'5. Document the shelving standard'}</h3><p>{video?'Record a short video showing the condition.':'Take a photo showing that every item is stored correctly.'}</p><div className={`qa-capture ${index===2?'qa-capture-zoom':''}`}>{src?(video?<video src={src} controls={index===2} muted playsInline preload="metadata"/>:<img src={src} alt="Shelving standard"/>):<MissingMedia video={video}/>}</div>{index>0&&<p className="qa-stamp">09-23-26 · 04:12:08 PM</p>}<button className="qa-primary" onClick={()=>setIndex(index===0?1:2)}>{index===0?(video?'Record video':'Take photo'):(video?'Play video':'Open photo')}</button>{index>0&&<p className="qa-success">✓ Attached to this mission</p>}</div></div>;}
  if(['self-rating','peer-rating'].includes(id))return <div className="qa-product"><Head title="Rate Missions"/><div className="qa-product-body"><MissionChip kind="Checklist" title="Closing Checklist" who="Anna F. - Staff" date="09-23-26" time="04:10 PM" pillTime="00:07:40" pillClass="chip--gray" showExec execTime="00:06:12"/><h3>{id==='self-rating'?'Rate your completed mission':'Peer ratings'}</h3>{(id==='self-rating'?['Anna F.']:index?['Ben R.','Carla M.']:['Ben R.']).map((person,i)=><section className="qa-rating" key={person}><span className="qa-avatar">{person[0]}</span><div><b>{person}</b><small>{id==='self-rating'?'Self-rating':'Peer rating'}</small><div className="qa-rating-buttons">{[1,2,3,4,5].map(n=><button key={n} aria-label={`Rate ${person} ${n} stars`} onClick={()=>setRating(n)}><Stars total={1} value={n<=(rating|| (index?4+i:0))?1:0} size={27}/></button>)}</div></div></section>)}</div></div>;
  if(id==='menu')return <div className="qa-product"><Head title="Kitchen" onMenu={()=>setMenu(!menu)}/><div className="qa-product-body"><p>Mission board</p></div>{menu&&<BoardMenu boardType="team" onDismiss={()=>setMenu(false)} onNavigate={()=>setMenu(false)}/>}</div>;
  const list=records.filter(record=>filter==='All media'||record.kind===filter);
  const single=['performed-by','timestamp'].includes(id);
  return <div className="qa-product"><Head title={opened?'Evidence':id==='gallery'?'Gallery':'Business Media'} onBack={()=>setOpened(null)}/><div className="qa-product-body">{!single&&!opened&&<div className="qa-filters">{['All media','Photo','Video'].map(value=><button aria-pressed={value===filter} className={value===filter?'is-selected':''} key={value} onClick={()=>setFilter(value)}>{value}</button>)}</div>}<div className={id==='gallery'&&!opened?'qa-evidence-grid':'qa-evidence-list'}>{(opened?[opened]:single?[records[0]]:list).map(record=><Evidence key={record.person+record.time} record={record} media={media} emphasis={id} onOpen={()=>setOpened(record)}/>)}</div>{opened?.kind==='Video'&&media.video&&<video src={media.video} controls playsInline/>}</div></div>;
}

export default function QualityAssetScreen({asset,device='mobile',initialState=0,media={},onStateChange}) {
  const [index,setIndex]=useState(initialState);
  const [menuTarget,setMenuTarget]=useState(null),[menuVisible,setMenuVisible]=useState(true);
  useEffect(()=>setIndex(initialState),[asset.id,initialState]);
  const fullBoard=['board','closed','menu'].includes(asset.id)&&!menuTarget;
  const isTablet=device==='tablet';
  const activeAsset=menuTarget?{...asset,id:menuTarget}:asset;
  const content=<Surface key={activeAsset.id} asset={activeAsset} index={index} setIndex={next=>{setIndex(next);onStateChange?.(next);}} media={media}/>;
  const demoState={missions:board,elapsed:0,selected:fullBoard?null:'sink',codeOpen:false};
  return <div className={`qa-screen qa-screen--${device} sp-preview--full`} data-asset={asset.id}>
    {isTablet&&asset.id==='gallery'?content:isTablet?<InteractiveMissionBoard device="tablet" referenceLayout initialScreen="board" initialMissions={board} demoState={demoState} demoDetail={content}/>:fullBoard?<div className="mi-interactive mi-interactive--phone mi-reference"><div className="ph-fit mi-phone"><PhoneShell title="Personal Board" onMenu={()=>setMenuVisible(true)} tabs={['Open','Claimed','Closed'].map(label=>({label,active:label===(asset.id==='closed'?'Closed':'Open')}))}><div className="mi-phone-cards">{board.filter(m=>m.status===(asset.id==='closed'?'closed':'open')).map(m=><MissionChip key={m.id} kind={m.type} title={m.title} points={m.points} reference={m.reference} who={m.performer} date={m.date} time={m.time} showExec={m.status==='closed'} execTime="00:06:12" pillTime="00:07:40" pillClass={m.status==='closed'?'chip--gray':'chip--green'}/>)}</div></PhoneShell></div></div>:content}
    {asset.id==='menu'&&menuVisible&&!menuTarget&&<div className="qa-manager-overlay"><button className="qa-manager-shade" aria-label="Dismiss manager menu" onClick={()=>setMenuVisible(false)}/><div className="qa-manager-menu"><button className="qa-manager-close" aria-label="Close manager menu" onClick={()=>setMenuVisible(false)}>×</button>{[['Personal Board','person'],['Switch Unit','building'],['Ticket Board','ticket'],['Rate Missions','like','self-rating'],['Knowledge Base','book','training'],['View Made Requests - 0','link'],['Make Request','plus'],['Add Process','process'],['Create Mission','file'],['Schedule to This Board','calendar'],['Business Media','image','business-media']].map(([label,icon,target])=>target?<button key={label} onClick={()=>setMenuTarget(target)}><MenuIcon kind={icon} menu="team"/><span>{label}</span></button>:<div key={label}><MenuIcon kind={icon} menu="team"/><span>{label}</span></div>)}</div></div>}
  </div>;
}
